### ISSUE TITLE
ansible-playbook fails with "No package matching 'isc-dhcp-server' is available"

### ISSUE THREAD

**Issue by chewrocca** [CumulusNetworks/cldemo-vagrant#7] opened 2016-07-13 16:25 UTC
After running vagrant up the ansible-playbook fails to install a package on oob-mgmt-server.  

TASK [services : run apt-get update] *******************************************
ok: [oob-mgmt-server]

TASK [services : install service packages] *************************************
failed: [oob-mgmt-server] => (item=[u'isc-dhcp-server', u'bind9']) => {"failed": true, "item": ["isc-dhcp-server", "bind9"], "msg": "No package matching 'isc-dhcp-server' is available"}

PLAY RECAP *********************************************************************
oob-mgmt-server            : ok=20   changed=16   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by isharacomix** [comment] 2016-07-28 19:34
I've gotten errors like these but they appear to be intermittent depending on how the network is behaving. Is this happening consistently?

**Comment by isharacomix** [comment] 2016-09-27 15:40
Closing. It seems like it was an intermittent failure, and I can't reproduce it. Let us know if you encounter it again.

**Closed by isharacomix** 2016-09-27 15:40 UTC
